use project;
show tables;
select * from cust;

#Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue
from cust 
group by gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount?
select * 
from cust 
where discount_applied = 'yes'
and purchase_amount>=(select avg(purchase_amount) from cust); 

# Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,avg(review_rating) as avg_rating
from cust
group by item_purchased 
order by avg(review_rating) desc
limit 5;

# 04. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,avg(purchase_amount) as avg_amount
from cust
where shipping_type in('standaed','express')
group by shipping_type ;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(*),
avg(purchase_amount) as avg_spent,
sum(purchase_amount) as total_amount
from cust
group by subscription_status;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
sum(case when discount_applied='yes' then 1 else 0 end)*100/count(*) as discount_per
from cust 
group by item_purchased
order by discount_per desc
limit 5;
# 07. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT customer_segment, COUNT(*)
FROM (
    SELECT 
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM cust
) AS segmented_customer
GROUP BY customer_segment;

# Q8. What are the top 3 most purchased products within each category?
SELECT category,iteam_purchased, total_purchases
FROM (
    SELECT 
        category,
        product_name,
        COUNT(*) AS total_purchases,
        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rnk
    FROM cust
    GROUP BY category, product_name
) ranked
WHERE rnk <= 3
ORDER BY category, total_purchases DESC;

#09. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(*)
from cust 
where previous_purchases>5
group by subscription_status;

#18. What is the revenue contribution of each age group?
select * from cust
select age_group,sum(purchase_amount) as total_revenue
from cust 
group by age_group
order by total_revenue desc
show tables;
select * from retail;